### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by kirantpatil** [bloom-solutions/borutus#36]
Hi,

I would like to know below details specific to borutus

1. Advantages of borutus compared to plutus.

2. Can we Destroy debits and credits amounts when entry is deleted

3. Any new feature or UI changes in pipeline ?

4. Are you using it in production ?

5. Will you accept any PR as enhancement ?

Thanks.

**Comment by ramontayag** [comment]
@kirantpatil 

> * Advantages of borutus compared to plutus.

I suggest going through https://github.com/bloom-solutions/borutus/blob/master/CHANGELOG.md to see if there's anything here that you need. :)

We did this because plutus stopped getting updates but we didn't want to rewrite it.

> * Can we Destroy debits and credits amounts when entry is deleted

We did not make changes here. You can if your code calls it, but I don't suggest you do to keep the ledger intact.

> * Any new feature or UI changes in pipeline ?

No, I think UI is something that actually should be outside of this gem.

> * Are you using it in production ?

We are.

> * Will you accept any PR as enhancement ?

Sure.

**Comment by kirantpatil** [comment]
Great. Thanks a lot.
